- .github/workflows/test-frontend.yml
- frontend/.prettierignore
- frontend/package.json
- frontend/src/components/ShipmentDialog.vue
- frontend/src/components/UserDialog.vue
- frontend/src/views/AdminConfigView.vue
> Frontend checks

- backend/src/services/user/login.test.ts
- backend/src/services/user/login.ts
- frontend/src/views/LoginView.vue
> option to stay logged in until midnight

- frontend/index.html
- frontend/nginx.conf
> website icon fix

- .github/workflows/test-frontend.yml
- .pre-commit-config.yaml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ShipmentDialog.vue
- frontend/src/lib/overview.test.ts
- frontend/src/lib/overview.ts
- frontend/src/lib/pdf/pdf.ts
- frontend/src/lib/pdf/zip.ts
- frontend/src/lib/shipment/prepareShipment.ts
- frontend/src/lib/shipment/shipmentOverviewPdf.ts
- frontend/src/lib/shipment/shipmentPackagingPdf.test.ts
- frontend/src/lib/shipment/shipmentPackagingPdf.ts
- frontend/src/lib/utils.ts
- frontend/src/testSetup.ts
- frontend/src/views/AdminOverview.vue
- frontend/testSetup.ts
- frontend/vite.config.ts
> Change default PDF table layout

- frontend/src/views/EmployeeShipmentView.vue
> show shipment description in overview #79

- frontend/src/views/EmployeeShipmentView.vue
> show icon dependent on shipment status

- CHANGELOG.md
- backend/src/database/Depot.ts
- backend/src/database/database.ts
- backend/src/index.ts
- backend/src/migrations/1726862542988-depot-rank.ts
- backend/src/services/config/saveDepot.test.ts
- backend/src/services/config/saveDepot.ts
- backend/src/services/config/updateDepot.ts
- backend/src/test/testHelpers.ts
- dev/new-release.bash
- frontend/src/lib/pdf/pdf.ts
- frontend/src/lib/shipment/shipmentOverviewPdf.test.ts
- frontend/src/lib/shipment/shipmentOverviewPdf.ts
- frontend/src/requests/depot.ts
- frontend/src/testSetup.ts
- frontend/src/views/AdminDepotView.vue
- shared/src/types.ts
> sortable depots

- frontend/src/App.vue
- frontend/src/components/BusyIndicator.vue
- frontend/src/components/ErrorDisplay.vue
- frontend/src/store/errorStore.ts
- frontend/src/views/AdminDepotView.vue
Ergänzung zu #96 
* Sortieranimation funktionert jetzt richtig (v-list/v-list-item wurde falsch verwendet)
* Busy-Indicator
* Zentralisiertes Error-Display
> Refine sortable depots 36

- CHANGELOG.md
- frontend/src/components/AppBar.vue
- frontend/src/main.ts
> toggle dark/light theme and persist in localStorage #102

- frontend/src/App.vue
- frontend/src/components/UiFeedbackDisplay.vue
- frontend/src/lang/lang.ts
- frontend/src/store/uiFeedbackStore.ts
- frontend/src/views/AdminConfigView.vue
- frontend/src/views/AdminDepotView.vue
> facilitate positive ui feedback

- CHANGELOG.md
- frontend/src/components/ShipmentCard.vue
- frontend/src/lang/lang.ts
> message on the shipment card

- CHANGELOG.md
- frontend/src/components/ShipmentItem.vue
> don't show depots with needed quantity = 0

- CHANGELOG.md
- frontend/src/components/AdditionalShipmentItem.vue
- frontend/src/components/ShipmentItem.vue
> select all depots for ShipmentItem

- CHANGELOG.md
- backend/src/index.ts
- backend/src/services/getVersion.ts
- frontend/src/components/MaintenanceBanner.vue
- frontend/src/lang/lang.ts
- frontend/src/requests/versionInfo.ts
- shared/src/types.ts
> display message when version out of date or server error

- CHANGELOG.md
- backend/package.json
- backend/src/database/database.ts
- backend/src/migrations/1730887882789-add-maintenance-msg-text.ts
- backend/src/services/getVersion.ts
- backend/src/services/initDb.ts
- backend/src/services/text/deleteTextContent.test.ts
- backend/src/services/text/deleteTextContent.ts
- backend/src/services/text/saveTextContent.test.ts
- backend/src/services/text/saveTextContent.ts
- backend/vitest.config.ts
- dev/DEVELOPMENT.md
- frontend/package.json
- frontend/src/components/MaintenanceBanner.vue
- frontend/src/components/TextContentDialog.vue
- frontend/src/lang/lang.ts
- frontend/src/views/AdminTextView.vue
- shared/src/enum.ts
- shared/src/types.ts
> let admins set the maintanance message

- CHANGELOG.md
- backend/src/database/ProductCategory.ts
- backend/src/database/database.ts
- backend/src/migrations/1731067417340-add-product-category-type.ts
- backend/src/services/bi/bi.ts
- backend/src/util/productUtil.ts
- backend/test/testHelpers.ts
- frontend/src/components/AppBar.vue
- frontend/src/components/HomeStatsCard.vue
- frontend/src/components/ProductCategoryDialog.vue
- frontend/src/components/products/ProductCategoryConfig.vue
- frontend/src/components/statistics/ProductStatistics.vue
- frontend/src/components/styled/SeasonText.vue
- frontend/src/lang/lang.ts
- frontend/src/routes.ts
- frontend/src/views/AdminProductsView.vue
- frontend/src/views/AdminStatisticsView.vue
- frontend/src/views/HomeView.vue
- shared/src/enum.ts
- shared/src/types.ts
> Adjust distribution diagrams

- CHANGELOG.md
- frontend/src/components/ShopDialog.vue
- frontend/src/lang/lang.ts
> confirm contribution model

- backend/src/index.ts
- backend/src/services/user/updateUser.ts
- frontend/src/requests/user.ts
- frontend/src/views/AdminUserView.vue
- shared/src/types.ts
> user table: multi select and activate/deactivate users

- backend/src/services/user/getUser.ts
- frontend/src/components/ShopDialog.vue
- frontend/src/requests/user.ts
- frontend/src/routes.ts
- frontend/src/views/AdminUserView.vue
- frontend/src/views/ShopView.vue
- shared/src/types.ts
> show last order change of current season in user table

- backend/src/services/getOverview.ts
- backend/src/services/order/saveOrder.ts
- frontend/src/components/ShopDialog.vue
- frontend/src/views/ShopView.vue
- shared/src/lang/lang.ts
- shared/src/msrp.ts
- shared/src/types.ts
> show separate selfgrown and cooperation msrps

- CHANGELOG.md
- backend/src/database/database.ts
- backend/src/migrations/1738274522237-organization-info-text-content.ts
- backend/src/migrations/1738317876884-pdf-text-content.ts
- backend/src/services/applicant/saveApplicant.ts
- backend/src/services/email/email.ts
- backend/src/services/email/emailHelper.ts
- backend/src/services/initDb.ts
- backend/src/services/order/saveOrder.ts
- backend/src/services/text/deleteTextContent.test.ts
- backend/src/services/text/getOrganizationInfo.ts
- backend/src/services/text/saveTextContent.test.ts
- backend/src/services/text/saveTextContent.ts
- frontend/src/components/ShipmentDialog.vue
- frontend/src/components/ShopDialog.vue
- frontend/src/components/text/TextContentDialog.vue
- frontend/src/lib/shipment/shipmentPackagingPdf.ts
- frontend/src/store/textContentStore.ts
- frontend/src/views/AdminOverview.vue
- frontend/src/views/AdminTextView.vue
- frontend/src/views/RegisterView.vue
- shared/src/config.ts
- shared/src/enum.ts
- shared/src/lang/lang.ts
- shared/src/pdf/overviewPdfs.ts
- shared/src/pdf/pdf.ts
- shared/src/text/textContent.ts
- shared/src/types.ts
> additinal footer info in packaging list

- CHANGELOG.md
- frontend/src/components/HomeStatsCard.vue
- frontend/src/components/ShopDialog.vue
- frontend/src/components/ShopItem.vue
- frontend/src/views/AdminUserView.vue
- frontend/src/views/ShopView.vue
> usability shop dialog

- CHANGELOG.md
- frontend/src/components/statistics/DistributionPlot.vue
- frontend/src/components/statistics/OrderStatistics.vue
> order valid from

- CHANGELOG.md
- backend/src/services/order/getOrder.ts
- backend/src/util/requestUtil.ts
- frontend/src/components/statistics/OrderStatistics.vue
- frontend/src/requests/shop.ts
- frontend/src/views/AdminUserView.vue
- shared/src/lang/lang.ts
- shared/src/types.ts
> more order stats

- CHANGELOG.md
- backend/src/services/getOverview.ts
- backend/src/services/order/saveOrder.ts
- backend/src/util/requestUtil.ts
- frontend/src/components/AppBar.vue
- frontend/src/requests/overview.ts
- frontend/src/views/AdminOverview.vue
- shared/src/lang/lang.ts
- shared/src/pdf/overviewPdfs.ts
- shared/src/types.ts
- shared/src/util/dateHelper.ts
> improved csv export

- CHANGELOG.md
- backend/src/services/order/getOrder.test.ts
- backend/src/services/order/saveOrder.ts
- backend/src/services/user/getUser.ts
- backend/src/services/user/saveUser.ts
- backend/src/services/user/updateUser.ts
- backend/test/testHelpers.ts
- frontend/src/components/ShipmentCard.vue
- frontend/src/components/ShopDialog.vue
- frontend/src/requests/user.ts
- frontend/src/store/userStore.ts
- frontend/src/views/AdminUserView.vue
- frontend/src/views/ShopView.vue
- shared/src/types.ts
> activate orders

- CHANGELOG.md
- frontend/src/components/ShipmentDialog.vue
- frontend/src/components/ShipmentItem.vue
- frontend/src/views/EmployeeShipmentView.vue
> Only count active deliveries

- CHANGELOG.md
- backend/src/database/Applicant.ts
- backend/src/index.ts
- backend/src/services/applicant/importApplicant.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/applicant/ApplicantView.vue
- frontend/src/components/import/CsvImportPanel.vue
- frontend/src/requests/applicant.ts
- frontend/src/views/AdminApplicantView.vue
- shared/src/types.ts
- shared/src/util/utils.ts
> import user data

- CHANGELOG.md
- frontend/src/components/statistics/OrderStatistics.vue
> Offer vs msrp

- CHANGELOG.md
- frontend/src/components/applicant/ApplicantTable.vue
- frontend/src/routes.ts
- frontend/src/views/AdminApplicantView.vue
- frontend/src/views/AdminUserView.vue
- shared/src/types.ts
- shared/src/util/utils.ts
> add comment column in user view and export

- CHANGELOG.md
- backend/src/database/ErrorLog.ts
- backend/src/database/database.ts
- backend/src/index.ts
- backend/src/middleware/errorLogger.ts
- backend/src/migrations/1743622159714-error-log.ts
- backend/src/services/getErrorLog.ts
- frontend/src/components/AppBar.vue
- frontend/src/requests/errorLog.ts
- frontend/src/routes.ts
- frontend/src/views/AdminStatusView.vue
- shared/src/types.ts
> error logging

- CHANGELOG.md
- backend/src/database/Shipment.ts
- backend/src/database/database.ts
- backend/src/migrations/1744143625480-shipment-revisions.ts
- backend/src/services/getUserFromContext.ts
- backend/src/services/shipment/getShipments.ts
- backend/src/services/shipment/saveShipment.test.ts
- backend/src/services/shipment/saveShipment.ts
- backend/src/services/user/getUser.ts
- backend/src/util/requestUtil.ts
- backend/testSetup.ts
- backend/vitest.config.ts
- frontend/src/components/Footer.vue
- frontend/src/components/ShipmentCard.vue
- frontend/src/components/ShipmentDialog.vue
- frontend/src/components/status/ErrorProtocol.vue
- frontend/src/lib/convert.test.ts
- frontend/src/lib/convert.ts
- frontend/src/lib/shipment/prepareShipment.ts
- frontend/src/requests/shipment.ts
- frontend/src/requests/user.ts
- frontend/src/store/versionInfoStore.ts
- frontend/src/views/AdminUserView.vue
- frontend/src/views/EmployeeShipmentView.vue
- shared/src/lang/lang.ts
- shared/src/types.ts
- shared/src/util/dateHelper.ts
> adjust past shipments

- CHANGELOG.md
- backend/src/services/bi/bi.ts
- frontend/src/components/ShopDialog.vue
> fix full depot selection

- CHANGELOG.md
- frontend/src/components/ShipmentItem.vue
>  highlight offset

- CHANGELOG.md
- frontend/src/lib/options.ts
- frontend/src/lib/shipment/shipmentPackagingPdf.test.ts
- frontend/src/lib/shipment/shipmentPackagingPdf.ts
- shared/src/pdf/pdf.ts
> improved shipment pdf

- CHANGELOG.md
- backend/src/services/order/saveOrder.test.ts
- frontend/src/components/ProductDialog.vue
- shared/src/validation/capacity.test.ts
- shared/src/validation/capacity.ts
> inactive product saving

- CHANGELOG.md
- backend/src/index.ts
- backend/src/services/shipment/getUserShipments.ts
- frontend/src/components/ShipmentCard.vue
- frontend/src/components/ShipmentDialog.vue
- frontend/src/components/shipment/DeliveryOverview.vue
- frontend/src/requests/shipment.ts
- frontend/src/views/EmployeeShipmentView.vue
> only show normal shipments to user

- CHANGELOG.md
- frontend/src/components/ShopItem.vue
- frontend/src/views/AdminUserView.vue
- shared/src/msrp.ts
> fixes after #227

- CHANGELOG.md
- backend/src/database/database.ts
- backend/src/migrations/1758569141622-page-element-texts.ts
- backend/src/services/initDb.ts
- backend/src/services/text/saveTextContent.ts
- frontend/src/components/text/TextContentDialog.vue
- frontend/src/views/AdminTextView.vue
- frontend/src/views/HomeView.vue
- shared/src/config.ts
- shared/src/enum.ts
- shared/src/lang/lang.ts
- shared/src/types.ts
> home page text

- CHANGELOG.md
- backend/src/services/shipment/deleteShipment.ts
- frontend/src/components/ShipmentDialog.vue
> delete shipment items when deleting shipment

- CHANGELOG.md
- backend/src/services/order/modifyOrder.ts
- backend/src/services/user/getUser.ts
- backend/src/services/user/updateUser.ts
- frontend/src/requests/user.ts
- frontend/src/views/AdminUserView.vue
- shared/src/types.ts
> delete unconfirmed orders

- CHANGELOG.md
- frontend/src/components/ShipmentDialog.vue
- frontend/src/lib/shipment/shipmentOverviewPdf.ts
- shared/src/pdf/pdf.ts
> 287 shipment overview header2

- CHANGELOG.md
- backend/src/services/initDb.ts
- backend/src/services/text/deleteTextContent.test.ts
- frontend/src/components/ShipmentCard.vue
- frontend/src/components/ShipmentDialog.vue
- frontend/src/lib/shipment/shipmentPackagingPdf.ts
- frontend/src/store/textContentStore.ts
- frontend/src/views/HomeView.vue
- shared/src/config.ts
- shared/src/lang/lang.ts
- shared/src/pdf/pdf.ts
- shared/src/text/textContent.ts
- shared/src/types.ts
> highlight product note
